controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.05
    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1     # meters
      movement_time_allowance: 3.0

    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2      # (meters) Tighten XY tolerance
      yaw_goal_tolerance: 3.14      # (radians) Tighten angle tolerance
      stateful: false               # Prevents re-checking past goals

    controller_plugins: ["FollowPath"]    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      # Allow high forward speed in straight open areas
      desired_linear_vel: 1.5          # top speed (used in straight open paths)
      min_approach_linear_velocity: 0.1
      # Rotation control
      use_rotate_to_heading: true
      rotate_to_heading_angular_vel: 2.0
      rotate_to_heading_min_angle: 0.2  # respond faster to angle mismatch

      allow_reversing: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0

global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[-0.3, -0.15], [-0.3, 0.15], [0.1, 0.15], [0.1, -0.15]]"

local_costmap:
  local_costmap:
    ros__parameters:
      footprint: "[[-0.3, -0.15], [-0.3, 0.15], [0.1, 0.15], [0.1, -0.15]]"

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [1.5, 0.0, 20.0]
    min_velocity: [-0.5, 0.0, -20.0]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    use_realtime_priority: false
    enable_stamped_cmd_vel: false