amcl:
  ros__parameters:
    use_map_topic: true  # Subscribe to SLAM map updates

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2      # (meters) Tighten XY tolerance
      yaw_goal_tolerance: 3.14      # (radians) Tighten angle tolerance
      stateful: false               # Prevents re-checking past goals

    controller_plugins: ["FollowPath"]    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_velocity: 1.2      # (m/s) Max forward speed
      max_angular_velocity: 0.8         # (rad/s) Reduce for stability
      use_rotate_to_heading: false
      use_final_approach_orientation: false

      use_holonomic: true               # Enable lateral motion (if needed)
      cost_scaling_dist: 0.5            # Aggressive obstacle avoidance
      inflation_cost_scaling_factor: 3.0 # Prioritize obstacle clearance

planner_server:
  ros__parameters:
    expected_update_rate: 1.0  # Adjust for real-time updates